version: '3.2'
services:
  fasterrunner2:
    image: fasterrunner:2.0
    container_name: fasterrunner2
    ports:
      - 5000:5000
    networks:
      - swarm_net
    environment:
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
networks:
  swarm_net:
    external: true
