version: '3.2'
services:
  fasterrunner-service:
    image: hub.c.163.com/wydydq/fasterrunner:latest
    container_name: fasterrunner
    ports:
    - 8000:8000
    networks:
    - swarm_net
    depends_on:
    - mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
  fasterweb-service:
    image: hub.c.163.com/wydydq/fasterweb:latest
    container_name: fasterweb
    ports:
    - 8082:8082
    networks:
    - swarm_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
networks:
  swarm_net:
    external: true