version: '3'
services:
  # 容器名
  fasterunner:
    build: /opt/autotest/FasterRunner
    image: fasterunner:2.0
    # 依赖
    depends_on:
      - mysql
    privileged: true
    # 共享目录到容器,每次启动容器会copy宿主机代码
    volumes:
      - /opt/autotest/FasterRunner:/share/fasterunner
    ports:
      - 8000:8000
    command: /bin/sh -c '\cp -rf /share/fasterunner/* /usr/src/app/ && python manage.py runserver 0.0.0.0:8000'

  fasterweb:
    build: /opt/autotest/FasterWeb
    image: fasterweb:2.0
    # 依赖
    privileged: true
    # 共享目录到容器,每次启动容器会copy宿主机代码
    volumes:
      - /opt/autotest/FasterWeb:/share/fasterweb
    ports:
      - 8082:8082
    command: /bin/sh -c '\cp -rf /share/fasterweb/default.conf /etc/nginx/conf.d/ && \cp -rf /share/fasterweb/dist/  /usr/share/nginx/html/ && nginx -g "daemon off;"'
