# mysql、fasterrunner和fasterweb部署

version: "3.2"
services:
  # 1、运行集群管理工具portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    environment:
      - constraint:node.role == manager
    networks:
      - swarm_net
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/poratiner:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        # 重试三次
        max_attempts: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
  # 2、运行mysql
  mysql:
    image: hub.c.163.com/library/mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - swarm_net
    volumes:
      - /data/var/lib/mysql:/var/lib/mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        # 重试三次
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  # 3、fasterrunner服务
  fasterrunner-service:
    # 镜像地址
    image: hub.c.163.com/wydydq/fasterrunner:latest
    # 容器名称
    container_name: fasterrunner
    ports:
      - "8000:8000"
    networks:
      # 加入集群网络
      - swarm_net
#    volumes:
#      - /data/var/fasterrunner:/usr/src/app/FasterRunner
    deploy:
      # 实例数量
      replicas: 1
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '1.0'
          # 内存限制
          memory: 256M
  
  # 4、fasterweb服务
  fasterweb-service:
    # 镜像地址
    image: hub.c.163.com/wydydq/fasterweb:latest
    # 容器名称
    container_name: fasterweb
    ports:
      - "8082:8082"
    networks:
      # 加入集群网络
      - swarm_net
    deploy:
      # 实例数量
      replicas: 1
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '1.0'
          # 内存限制
          memory: 256M

networks:
  swarm_net:
    external: true
  